### ISSUE TITLE
Special Characters, Space and Links

### ISSUE THREAD

**Issue by lbmankala** [Vereyon/HtmlRuleSanitizer#14]
Hi There,

The library works fine for me except for some of the special characters. Changing the html text of some special characters to some unicode format is the problem for me. 
For instance, 
This is initial text.
![initial2](https://cloud.githubusercontent.com/assets/16317385/24253941/a7777278-1007-11e7-9b9d-84b5cea6839c.jpg)
Sanitized:
![sanitized2](https://cloud.githubusercontent.com/assets/16317385/24253976/bb0c6028-1007-11e7-9963-992939fafa48.jpg)

Initial: 
![initial_link](https://cloud.githubusercontent.com/assets/16317385/24253997/cb8f86f0-1007-11e7-911f-5d4c70bc6fc0.jpg)
Sanitized: 
![sanitized_link](https://cloud.githubusercontent.com/assets/16317385/24254007/d2a26d4a-1007-11e7-86b6-4452f1ad1721.jpg)

Initial:
![initial_symbol](https://cloud.githubusercontent.com/assets/16317385/24254029/df035568-1007-11e7-88fc-2f2741829957.jpg)
Sanitized:
![sanitized_symbol](https://cloud.githubusercontent.com/assets/16317385/24254052/eaafa92a-1007-11e7-8ff1-cf54df0ff749.jpg)

I don't want these changes to happen, is there anyway to prevent this or put them in white list or so?

Thanks,
Laxman Mankala

**Comment by cakkermans** [comment]
The `&nbsp;` getting replaced by `&#160;` is due to the HTML entities encoder of the .NET framework. &nbsp; are equivalent `&#160;`, but unfortunately we do not have control over wether the `&nbsp;` or `&#160;` is used to represent a non breaking space character without writing our own entity encoder. I consider writing my own a tricky job.

The slash getting added to the URL is weird, I'll have to look into that. It should not happen.

The last problem with the omega and trademark is an encoding issue. The sanitizer returns and UTF-8 encoded string. HTML allows for optional escaping of characters outside the ASCII space and for some characters there are named entity escape sequences (such as `&reg;`, `&trade;`, etc.) I'll took into allowing more control over this as well, but again this may be tricky as we just pass the content to be encoded to the .NET HTML entity encoder.

Are the escape sequences causing you any actual trouble?

**Comment by cakkermans** [comment]
Closing this issue due to a lack of feedback.
